# The Assignment Problem

There are $n$ people available to carry out $n$ jobs. Each person is assigned to carry out exactly one job. Some individuals are better suited to particular jobs than others, so there is an estimated cost $c_{ij}$ if person $i$ is assigned to job $j$. The problem is to find a minimum cost assignment.

## Decision Variables

$$
x_{ij} =
\begin{cases}
1 & \text{if person } i \text{ is assigned to job } j \\
0 & \text{otherwise}
\end{cases}
$$

## Constraints

1. Each person does exactly one job:

$$
\sum_{j=1}^{n} x_{ij} = 1 \quad \text{for } i = 1, \ldots, n.
$$

2. Each job is done by exactly one person:

$$
\sum_{i=1}^{n} x_{ij} = 1 \quad \text{for } j = 1, \ldots, n.
$$

3. Binary constraints:

$$
x_{ij} \in \{0, 1\} \quad \text{for } i = 1, \ldots, n, \ j = 1, \ldots, n.
$$

## Objective Function

Minimize the total assignment cost:

$$
\min \sum_{i=1}^{n} \sum_{j=1}^{n} c_{ij} x_{ij}.
$$

## Complete Formulation

$$
\begin{aligned}
& \min \sum_{i=1}^{n} \sum_{j=1}^{n} c_{ij} x_{ij} \\
& \text{subject to:} \\
& \quad \sum_{j=1}^{n} x_{ij} = 1, \quad i = 1, \ldots, n \\
& \quad \sum_{i=1}^{n} x_{ij} = 1, \quad j = 1, \ldots, n \\
& \quad x_{ij} \in \{0, 1\}, \quad i = 1, \ldots, n, \ j = 1, \ldots, n
\end{aligned}
$$


In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment
import random

In [2]:
cost_matrix = np.array([
    [9, 2, 7, 8],
    [6, 4, 3, 7],
    [5, 8, 1, 8],
    [7, 6, 9, 4]
])

print("Cost Matrix:")
print(cost_matrix)

row_ind, col_ind = linear_sum_assignment(cost_matrix)
print("\nOptimal assignment:")
for r, c in zip(row_ind, col_ind):
  print(f"  Worker {r+1} → Job {c+1} (cost={cost_matrix[r, c]})")
print(f"Total optimal cost: {cost_matrix[row_ind, col_ind].sum()}\n")

Cost Matrix:
[[9 2 7 8]
 [6 4 3 7]
 [5 8 1 8]
 [7 6 9 4]]

Optimal assignment:
  Worker 1 → Job 2 (cost=2)
  Worker 2 → Job 1 (cost=6)
  Worker 3 → Job 3 (cost=1)
  Worker 4 → Job 4 (cost=4)
Total optimal cost: 13



In [3]:
costs = {
    "W1": {"J1": 9, "J2": 2, "J3": 7, "J4": 8},
    "W2": {"J1": 6, "J2": 4, "J3": 3, "J4": 7},
    "W3": {"J1": 5, "J2": 8, "J3": 1, "J4": 8},
    "W4": {"J1": 7, "J2": 6, "J3": 9, "J4": 4},
}

workers = list(costs.keys())
jobs = list(costs[workers[0]].keys())
cost_matrix = np.array([[costs[w][j] for j in jobs] for w in workers])

print("Cost Matrix (from dictionary):")
print(cost_matrix)

row_ind, col_ind = linear_sum_assignment(cost_matrix)
print("\nOptimal assignment:")
for r, c in zip(row_ind, col_ind):
  print(f"  {workers[r]} → {jobs[c]} (cost={cost_matrix[r, c]})")
print(f"Total optimal cost: {cost_matrix[row_ind, col_ind].sum()}\n")

Cost Matrix (from dictionary):
[[9 2 7 8]
 [6 4 3 7]
 [5 8 1 8]
 [7 6 9 4]]

Optimal assignment:
  W1 → J2 (cost=2)
  W2 → J1 (cost=6)
  W3 → J3 (cost=1)
  W4 → J4 (cost=4)
Total optimal cost: 13



In [4]:
n = 8   # number of workers/jobs
random.seed(10)
cost_matrix = np.array([[random.randint(1, 20) for _ in range(n)] for _ in range(n)])

print(f"Number of workers/jobs: {n}")
print("Cost Matrix:")
print(cost_matrix)

row_ind, col_ind = linear_sum_assignment(cost_matrix)
print("\nOptimal assignment:")
for r, c in zip(row_ind, col_ind):
  print(f"  Worker {r+1} → Job {c+1} (cost={cost_matrix[r, c]})")
print(f"Total optimal cost: {cost_matrix[row_ind, col_ind].sum()}")

Number of workers/jobs: 8
Cost Matrix:
[[19  2 14 16 19  1  7 15]
 [16  9  6  2 17 16 11  3]
 [ 8 12  2 14  5 20 12 13]
 [14 10  9 15  6 10 12  5]
 [15  8 15 20 13  2 19  1]
 [ 8  5  7 10 18 12  8 11]
 [18 15 14 16  3 19 11 17]
 [ 6  8 14  8  2  2 16 10]]

Optimal assignment:
  Worker 1 → Job 2 (cost=2)
  Worker 2 → Job 4 (cost=2)
  Worker 3 → Job 3 (cost=2)
  Worker 4 → Job 8 (cost=5)
  Worker 5 → Job 6 (cost=2)
  Worker 6 → Job 7 (cost=8)
  Worker 7 → Job 5 (cost=3)
  Worker 8 → Job 1 (cost=6)
Total optimal cost: 30
